apiVersion: batch/v1 
kind: Job 
metadata: 
  name: autoagora-model-gen
spec: 
  template:
    spec:
      containers: 
        - name: autoagora-model-gen
          image: us.gcr.io/graph-indexer-semiotic/autoagora_model_generator
          imagePullPolicy: Always
          env:
            - name: LOGS_POSTGRES_HOST
              value: postgres-autoagora
            - name: LOGS_POSTGRES_DATABASE
              value: autoagora
            - name: LOGS_POSTGRES_USERNAME
              value: autoagora
            - name: LOGS_POSTGRES_PASSWORD
              value: let-me-in
            - name: INDEXER_AGENT_MGMT_ENDPOINT
              value: http://indexer-agent:8000
            - name: INDEXER_SERVICE_METRICS_ENDPOINT
              value: http://indexer-service:7300/metrics
            - name: LOG_LEVEL
              value: DEBUG


      restartPolicy: Never
  backoffLimit: 1
