name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write

    outputs:
      new_release_published: ${{ steps.release.outputs.new_release_published }}
      new_release_major_version: ${{ steps.release.outputs.new_release_major_version }}
      new_release_minor_version: ${{ steps.release.outputs.new_release_minor_version }}
      new_release_patch_version: ${{ steps.release.outputs.new_release_patch_version }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      id: release
      uses: aasseman/python-semantic-release@gh_outputs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
